### ISSUE TITLE
How about the effect of OHEM?

### ISSUE THREAD

**Issue by huixiancheng** [placeforyiming/IROS21-FIDNet-SemanticKITTI#5]
This code is about ohem? Is there some ablation experiment showing result?https://github.com/placeforyiming/IROS21-FIDNet-SemanticKITTI/blob/7f90b45a765b8bba042b25f642cf12d8fccb5bc2/semantic_main.py#L180-L185

**Comment by huixiancheng** [comment]
More, Why do we need to multiply proj_range by range_mask then weighted loss? Feel confuse
https://github.com/placeforyiming/IROS21-FIDNet-SemanticKITTI/blob/7f90b45a765b8bba042b25f642cf12d8fccb5bc2/dataloader/Dataset_semanticKITTI.py#L120-L125

https://github.com/placeforyiming/IROS21-FIDNet-SemanticKITTI/blob/7f90b45a765b8bba042b25f642cf12d8fccb5bc2/semantic_main.py#L175-L179

**Comment by huixiancheng** [comment]
Also, looke like method predictions will ingnore missing. Is this cause by train with normal or ohem? 
Top is come from your pipeline with default configs. Bottom it's train without normal and ohem.  (Pics from top to bottom is Rang Image || Predictions || GT)
However, when I train without normal but with ohem , it's very frequencly to cause nan loss. (As same as show in your paper, "We empirically find adding a normal vector for each point will make the training more stable")
![下载](https://user-images.githubusercontent.com/65054204/135867441-5087fec7-c70d-4ad1-bd95-0f2a2bfda9d3.png)
![下载 (1)](https://user-images.githubusercontent.com/65054204/135869176-32efb287-a49e-48b7-9652-7e264496b34c.png)

**Comment by placeforyiming** [comment]
1. The online hard ming is a popular choice used in many semantic models. I don't have the ablation study for this part.
2. The weight is used to balance the importance of points. The LiDAR will receive too many points from close objects, so balance them with their distance is a heuristic weighting mechanism.
3. Any network will give you a full prediction on the range image. The label provided by KITTI is not full because of the dataset itself and some flaws of the lidar sensor on the transparent surface.
4.  The normal is helpful
